name: 🐞 Bug Report
description: Report a bug or unexpected behavior in Telegram Bot Spring Boot Starter
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!  
        Please fill out the details below to help us reproduce and fix the issue.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "For example: UpdateDispatcher fails when receiving edited messages"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please provide steps, code snippets, or configuration to reproduce the issue.
      placeholder: |
        1. Create a new Spring Boot app
        2. Add telegram-bot-spring-boot-starter dependency
        3. Configure long polling mode
        4. Observe error in logs
  - type: input
    id: version
    attributes:
      label: Library version
      description: Version of telegram-bot-spring-boot-starter you are using.
      placeholder: "e.g. 1.0.0"
  - type: input
    id: spring
    attributes:
      label: Spring Boot version
      placeholder: "e.g. 3.3.3"
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or stack trace
      render: shell
      placeholder: "Paste logs here (remove sensitive data)"
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "What did you expect to happen?"
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "What actually happened?"